[env] 
TERM="xterm-256color"

[general]
live_config_reload = true

[window]
decorations = "Full"
opacity = 1.0 
blur = false 
padding = { x = 3, y = 3 }

[scrolling]
multiplier = 5

[font]
normal = { family = "Cascadia Mono", style = "Regular" }
bold = { family = "Cascadia Mono", style = "Bold" }
offset = { x = 0, y = 1 }
size = 14 

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#111111"
red = "#bf1d1d"
green = "#15a115"
yellow = "#fdda0d"
blue = "#4646e0"
magenta = "#ba20b0"
cyan = "#20bab5"
white = "#ffffff"

[colors.bright]
black = "#555555"
red = "#9f4949"
green = "#4e9a4e"
yellow = "#dfb845"
blue = "#6e6ec3"
magenta = "#954c94"
cyan = "#4c9794"
white = "#ffffff"

[bell]
duration = 250 
animation = "EaseOut"
